Name:           kernelgen
Version:        0.1
Release:        alpha
Summary:        Compiler with automatic generation of GPU kernels from Fortran source code 
Source0:	ftp://upload.hpcforge.org/pub/kernelgen/llvm-r136600.tar.gz
Source1:	ftp://upload.hpcforge.org/pub/kernelgen/gcc-4.5-r177629.tar.gz
Source2:	ftp://upload.hpcforge.org/pub/kernelgen/dragonegg-r136347.tar.gz
Source3:	ftp://upload.hpcforge.org/pub/kernelgen/kernelgen-r357.tar.gz
Patch0:		llvm.varargs.patch
Patch1:		llvm.patch
Patch2:		llvm.gpu.patch
Patch3:		gcc.patch
Patch4:		gcc.opencl.patch
Patch5:		dragonegg.opencl.patch

Group:          Applications/Engineering
License:        GPL/BSD/Freeware
URL:            https://hpcforge.org/projects/kernelgen/

BuildRequires:  gcc-gfortran perl elfutils-libelf-devel libffi-devel gmp-devel mpfr-devel libmpc-devel flex glibc-devel
Requires:       gcc-gfortran perl elfutils-libelf libffi gmp mpfr libmpc perl-IPC-Run3 perl-XML-LibXSLT

Packager:       Dmitry Mikushin <dmikushin@nvidia.com>

%description
KGen is a tool for automatic generation of GPU kernels from Fortran source code. From user's point of view it acts as regular Fortran compiler.


%prep
rm -rf $RPM_BUILD_DIR/llvm
tar -xf llvm-r136600.tar.gz
rm -rf $RPM_BUILD_DIR/gcc-4.5
tar -xf gcc-4.5-r177629.tar.gz
rm -rf $RPM_BUILD_DIR/dragonegg
tar -xf dragonegg-r136347.tar.gz
rm -rf $RPM_BUILD_DIR/kernelgen
tar -xf kernelgen-r357.tar.gz

%patch0 -p1
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1


%build
cd $RPM_BUILD_DIR/llvm
mkdir build
cp -rf include/ build/include/
cd build
../configure --enable-jit --enable-optimized --enable-shared --prefix=$RPM_BUILD_ROOT/opt/kgen --enable-targets=host,cbe
make -j12 CXXFLAGS=-O3
cd $RPM_BUILD_DIR/gcc-4.5
mkdir build
cd build/
../configure --prefix=$RPM_BUILD_ROOT/opt/kgen --program-prefix=dragonegg- --enable-languages=c,fortran --with-mpfr-include=/usr/include/ --with-mpfr-lib=/usr/lib64 --with-gmp-include=/usr/include/ --with-gmp-lib=/usr/lib64 --enable-plugin
make -j12
cd $RPM_BUILD_DIR/kernelgen/trunk
./configure
make src


%install
cd $RPM_BUILD_DIR/llvm/build
make install
cd $RPM_BUILD_DIR/gcc-4.5/build
make install
cd $RPM_BUILD_DIR/dragonegg
GCC=$RPM_BUILD_ROOT/opt/kgen/bin/dragonegg-gcc LLVM_CONFIG=$RPM_BUILD_ROOT/opt/kgen/bin/llvm-config make
cp dragonegg.so $RPM_BUILD_ROOT/opt/kgen/lib64/
cd $RPM_BUILD_DIR/kernelgen/trunk
PREFIX=$RPM_BUILD_ROOT make install


%clean
rm -rf $RPM_BUILD_DIR/llvm
rm -rf $RPM_BUILD_DIR/gcc
rm -rf $RPM_BUILD_DIR/dragonegg
rm -rf $RPM_BUILD_DIR/kernelgen


%files
/opt/kgen/bin/kgen
/opt/kgen/bin/kgen-cpu
/opt/kgen/bin/kgen-cuda
/opt/kgen/bin/kgen-exec
/opt/kgen/bin/kgen-gforscale
/opt/kgen/bin/kgen-gfortran
/opt/kgen/bin/kgen-ocl
/opt/kgen/bin/kgen-opencl
/opt/kgen/include/gforscale.dragonegg.mod
/opt/kgen/include/gforscale.h
/opt/kgen/include/gforscale.mod
/opt/kgen/transforms/split/ALGORITHM
/opt/kgen/transforms/split/cosmo-do-portable.xsl
/opt/kgen/transforms/split/de-cpp.xsl
/opt/kgen/transforms/split/device/cpu/cpu.xsl
/opt/kgen/transforms/split/device/cpu/scenes
/opt/kgen/transforms/split/device/cpu/steps
/opt/kgen/transforms/split/device/cpu/txt.output.xsl
/opt/kgen/transforms/split/device/cuda/cuda.xsl
/opt/kgen/transforms/split/device/cuda/scenes
/opt/kgen/transforms/split/device/cuda/steps
/opt/kgen/transforms/split/device/cuda/txt.output.xsl
/opt/kgen/transforms/split/device/opencl/opencl.xsl
/opt/kgen/transforms/split/device/opencl/scenes
/opt/kgen/transforms/split/device/opencl/steps
/opt/kgen/transforms/split/device/opencl/txt.output.xsl
/opt/kgen/transforms/split/device/scenes
/opt/kgen/transforms/split/device/steps
/opt/kgen/transforms/split/do-grid.xsl
/opt/kgen/transforms/split/do-group.xsl
/opt/kgen/transforms/split/do-head.xsl
/opt/kgen/transforms/split/do-links.xsl
/opt/kgen/transforms/split/do-ndims.xsl
/opt/kgen/transforms/split/do-portable.xsl
/opt/kgen/transforms/split/do-rate.xsl
/opt/kgen/transforms/split/host/cxx/cxx.xsl
/opt/kgen/transforms/split/host/cxx/scenes
/opt/kgen/transforms/split/host/cxx/steps
/opt/kgen/transforms/split/host/cxx/txt.output.xsl
/opt/kgen/transforms/split/host/fortran/fortran.xsl
/opt/kgen/transforms/split/host/fortran/scenes
/opt/kgen/transforms/split/host/fortran/steps
/opt/kgen/transforms/split/host/fortran/txt.output.xsl
/opt/kgen/transforms/split/host/scenes
/opt/kgen/transforms/split/host/site/descs.xsl
/opt/kgen/transforms/split/host/site/scenes
/opt/kgen/transforms/split/host/site/site.xsl
/opt/kgen/transforms/split/host/site/steps
/opt/kgen/transforms/split/host/site/txt.output.xsl
/opt/kgen/transforms/split/host/steps
/opt/kgen/transforms/split/scenes
/opt/kgen/transforms/split/stage.01.xsl
/opt/kgen/transforms/split/stage.02.xsl
/opt/kgen/transforms/split/stage.03.xsl
/opt/kgen/transforms/split/stage.04.xsl
/opt/kgen/transforms/split/stage.06.xsl
/opt/kgen/transforms/split/stage.07.xsl
/opt/kgen/transforms/split/stage.08.xsl
/opt/kgen/transforms/split/stage.09.xsl
/opt/kgen/transforms/split/stage.10.xsl
/opt/kgen/transforms/split/stage.11.xsl
/opt/kgen/transforms/split/stage.12.xsl
/opt/kgen/transforms/split/stage.15.xsl
/opt/kgen/transforms/split/steps
/opt/kgen/bin/llc
/opt/kgen/bin/opt
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/crtbegin.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/crtbeginS.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/crtbeginT.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/crtend.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/crtendS.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/crtfastmath.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/crtprec32.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/crtprec64.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/crtprec80.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/libgcc.a
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/libgcc_eh.a
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/libgcov.a
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/libgfortranbegin.a
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/32/libgfortranbegin.la
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/crtbegin.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/crtbeginS.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/crtbeginT.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/crtend.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/crtendS.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/crtfastmath.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/crtprec32.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/crtprec64.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/crtprec80.o
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/finclude/omp_lib.dragonegg.mod
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/finclude/omp_lib.f90
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/finclude/omp_lib.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/finclude/omp_lib_kinds.dragonegg.mod
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include-fixed/README
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include-fixed/limits.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include-fixed/linux/a.out.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include-fixed/syslimits.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/abmintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/ammintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/avxintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/bmmintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/cpuid.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/cross-stdarg.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/emmintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/float.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/fma4intrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/ia32intrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/immintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/iso646.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/lwpintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/mf-runtime.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/mm3dnow.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/mm_malloc.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/mmintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/nmmintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/omp.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/pmmintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/popcntintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/smmintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/ssp/ssp.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/ssp/stdio.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/ssp/string.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/ssp/unistd.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/stdarg.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/stdbool.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/stddef.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/stdfix.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/stdint-gcc.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/stdint.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/tmmintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/unwind.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/varargs.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/wmmintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/x86intrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/xmmintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/include/xopintrin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/install-tools/fixinc_list
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/install-tools/gsyslimits.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/install-tools/include/README
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/install-tools/include/limits.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/install-tools/macro_list
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/install-tools/mkheaders.conf
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/libgcc.a
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/libgcc_eh.a
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/libgcov.a
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/libgfortranbegin.a
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/libgfortranbegin.la
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/ada/gcc-interface/ada-tree.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/alias.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/all-tree.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/ansidecl.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/auto-host.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/b-header-vars
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/basic-block.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/bitmap.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/builtins.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/bversion.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/c-common.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/c-common.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/c-pragma.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/c-pretty-print.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/cfghooks.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/cfgloop.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/cgraph.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/cif-code.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/dbxelf.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/elfos.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/glibc-stdint.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/i386/att.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/i386/biarch64.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/i386/i386-protos.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/i386/i386.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/i386/linux64.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/i386/unix.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/i386/x86-64.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/linux.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/svr4.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/config/vxworks-dummy.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/configargs.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/coretypes.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/cp/cp-tree.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/cppdefault.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/cpplib.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/debug.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/defaults.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/diagnostic.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/diagnostic.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/double-int.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/emit-rtl.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/except.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/filenames.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/fixed-value.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/flags.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/function.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/gcc-plugin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/genrtl.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/ggc.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/gimple.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/gimple.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/gsstruct.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/gtype-desc.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/hard-reg-set.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/hashtab.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/highlev-plugin-common.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/hwint.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/incpath.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/input.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/insn-constants.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/insn-flags.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/insn-modes.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/insn-notes.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/intl.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/ipa-prop.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/ipa-reference.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/ipa-utils.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/java/java-tree.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/langhooks.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/libiberty.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/line-map.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/machmode.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/md5.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/mode-classes.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/objc/objc-tree.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/obstack.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/omp-builtins.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/options.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/opts.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/output.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/params.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/params.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/partition.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/plugin-version.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/plugin.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/plugin.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/pointer-set.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/predict.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/predict.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/prefix.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/pretty-print.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/real.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/reg-notes.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/rtl.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/rtl.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/safe-ctype.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/sbitmap.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/splay-tree.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/statistics.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/symtab.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/sync-builtins.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/system.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/target.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/timevar.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/timevar.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tm-preds.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tm.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tm_p.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/toplev.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tree-check.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tree-dump.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tree-flow-inline.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tree-flow.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tree-inline.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tree-iterator.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tree-pass.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tree-ssa-alias.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tree-ssa-operands.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tree-ssa-sccvn.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tree.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/tree.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/treestruct.def
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/varray.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/vec.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/vecprim.h
/opt/kgen/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/plugin/include/version.h
/opt/kgen/lib/libCompilerDriver.a
/opt/kgen/lib/libEnhancedDisassembly.a
/opt/kgen/lib/libEnhancedDisassembly.so
/opt/kgen/lib/libLLVM-3.0svn.so
/opt/kgen/lib/libLTO.so
/opt/kgen/lib/libgcc_s.so
/opt/kgen/lib/libgcc_s.so.1
/opt/kgen/lib/libgfortran.so
/opt/kgen/lib/libgfortran.so.3
/opt/kgen/lib/libgfortran.so.3.0.0
/opt/kgen/lib/libgomp.so
/opt/kgen/lib/libgomp.so.1
/opt/kgen/lib/libgomp.so.1.0.0
/opt/kgen/lib/libmudflap.so
/opt/kgen/lib/libmudflap.so.0
/opt/kgen/lib/libmudflap.so.0.0.0
/opt/kgen/lib/libmudflapth.so
/opt/kgen/lib/libmudflapth.so.0
/opt/kgen/lib/libmudflapth.so.0.0.0
/opt/kgen/lib/libprofile_rt.so
/opt/kgen/lib/libssp.so
/opt/kgen/lib/libssp.so.0
/opt/kgen/lib/libssp.so.0.0.0
/opt/kgen/lib64/libgcc_s.so
/opt/kgen/lib64/libgcc_s.so.1
/opt/kgen/lib64/libgfortran.a
/opt/kgen/lib64/libgfortran.la
/opt/kgen/lib64/libgfortran.so
/opt/kgen/lib64/libgfortran.so.3
/opt/kgen/lib64/libgfortran.so.3.0.0
/opt/kgen/lib64/libgomp.so
/opt/kgen/lib64/libgomp.so.1
/opt/kgen/lib64/libgomp.so.1.0.0
/opt/kgen/lib64/libgomp.spec
/opt/kgen/lib64/libiberty.a
/opt/kgen/lib64/libmudflap.so
/opt/kgen/lib64/libmudflap.so.0
/opt/kgen/lib64/libmudflap.so.0.0.0
/opt/kgen/lib64/libmudflapth.so
/opt/kgen/lib64/libmudflapth.so.0
/opt/kgen/lib64/libmudflapth.so.0.0.0
/opt/kgen/lib64/libssp.so
/opt/kgen/lib64/libssp.so.0
/opt/kgen/lib64/libssp.so.0.0.0
/opt/kgen/libexec/gcc/x86_64-unknown-linux-gnu/4.5.4/cc1
/opt/kgen/libexec/gcc/x86_64-unknown-linux-gnu/4.5.4/collect2
/opt/kgen/libexec/gcc/x86_64-unknown-linux-gnu/4.5.4/f951
/opt/kgen/libexec/gcc/x86_64-unknown-linux-gnu/4.5.4/install-tools/fixinc.sh
/opt/kgen/libexec/gcc/x86_64-unknown-linux-gnu/4.5.4/install-tools/fixincl
/opt/kgen/libexec/gcc/x86_64-unknown-linux-gnu/4.5.4/install-tools/mkheaders
/opt/kgen/libexec/gcc/x86_64-unknown-linux-gnu/4.5.4/install-tools/mkinstalldirs
/opt/kgen/libexec/gcc/x86_64-unknown-linux-gnu/4.5.4/lto-wrapper
/opt/kgen/libexec/gcc/x86_64-unknown-linux-gnu/4.5.4/lto1
/opt/kgen/lib64/dragonegg.so


%exclude
/opt/kgen/bin/bugpoint
/opt/kgen/bin/dragonegg-cpp
/opt/kgen/bin/dragonegg-gcc
/opt/kgen/bin/dragonegg-gccbug
/opt/kgen/bin/dragonegg-gcov
/opt/kgen/bin/dragonegg-gfortran
/opt/kgen/bin/g95xml-refids
/opt/kgen/bin/g95xml-tree
/opt/kgen/bin/lli
/opt/kgen/bin/llvm-ar
/opt/kgen/bin/llvm-as
/opt/kgen/bin/llvm-bcanalyzer
/opt/kgen/bin/llvm-config
/opt/kgen/bin/llvm-diff
/opt/kgen/bin/llvm-dis
/opt/kgen/bin/llvm-extract
/opt/kgen/bin/llvm-ld
/opt/kgen/bin/llvm-link
/opt/kgen/bin/llvm-mc
/opt/kgen/bin/llvm-nm
/opt/kgen/bin/llvm-objdump
/opt/kgen/bin/llvm-prof
/opt/kgen/bin/llvm-ranlib
/opt/kgen/bin/llvm-rtdyld
/opt/kgen/bin/llvm-stub
/opt/kgen/bin/llvmc
/opt/kgen/bin/macho-dump
/opt/kgen/bin/tblgen
/opt/kgen/bin/x86_64-unknown-linux-gnu-dragonegg-gcc
/opt/kgen/bin/x86_64-unknown-linux-gnu-dragonegg-gfortran
/opt/kgen/bin/x86_64-unknown-linux-gnu-gcc-4.5.4
/opt/kgen/docs/llvm/html.tar.gz
/opt/kgen/docs/llvm/html/AliasAnalysis.html
/opt/kgen/docs/llvm/html/BitCodeFormat.html
/opt/kgen/docs/llvm/html/BranchWeightMetadata.html
/opt/kgen/docs/llvm/html/Bugpoint.html
/opt/kgen/docs/llvm/html/CFEBuildInstrs.html
/opt/kgen/docs/llvm/html/CMake.html
/opt/kgen/docs/llvm/html/CodeGenerator.html
/opt/kgen/docs/llvm/html/CodingStandards.html
/opt/kgen/docs/llvm/html/CommandGuide/FileCheck.html
/opt/kgen/docs/llvm/html/CommandGuide/bugpoint.html
/opt/kgen/docs/llvm/html/CommandGuide/index.html
/opt/kgen/docs/llvm/html/CommandGuide/lit.html
/opt/kgen/docs/llvm/html/CommandGuide/llc.html
/opt/kgen/docs/llvm/html/CommandGuide/lli.html
/opt/kgen/docs/llvm/html/CommandGuide/llvm-ar.html
/opt/kgen/docs/llvm/html/CommandGuide/llvm-as.html
/opt/kgen/docs/llvm/html/CommandGuide/llvm-bcanalyzer.html
/opt/kgen/docs/llvm/html/CommandGuide/llvm-config.html
/opt/kgen/docs/llvm/html/CommandGuide/llvm-diff.html
/opt/kgen/docs/llvm/html/CommandGuide/llvm-dis.html
/opt/kgen/docs/llvm/html/CommandGuide/llvm-extract.html
/opt/kgen/docs/llvm/html/CommandGuide/llvm-ld.html
/opt/kgen/docs/llvm/html/CommandGuide/llvm-link.html
/opt/kgen/docs/llvm/html/CommandGuide/llvm-nm.html
/opt/kgen/docs/llvm/html/CommandGuide/llvm-prof.html
/opt/kgen/docs/llvm/html/CommandGuide/llvm-ranlib.html
/opt/kgen/docs/llvm/html/CommandGuide/llvmc.html
/opt/kgen/docs/llvm/html/CommandGuide/llvmgcc.html
/opt/kgen/docs/llvm/html/CommandGuide/llvmgxx.html
/opt/kgen/docs/llvm/html/CommandGuide/manpage.css
/opt/kgen/docs/llvm/html/CommandGuide/opt.html
/opt/kgen/docs/llvm/html/CommandGuide/tblgen.html
/opt/kgen/docs/llvm/html/CommandLine.html
/opt/kgen/docs/llvm/html/CompilerDriver.html
/opt/kgen/docs/llvm/html/CompilerDriverTutorial.html
/opt/kgen/docs/llvm/html/CompilerWriterInfo.html
/opt/kgen/docs/llvm/html/DebuggingJITedCode.html
/opt/kgen/docs/llvm/html/DeveloperPolicy.html
/opt/kgen/docs/llvm/html/ExceptionHandling.html
/opt/kgen/docs/llvm/html/ExtendingLLVM.html
/opt/kgen/docs/llvm/html/FAQ.html
/opt/kgen/docs/llvm/html/GCCFEBuildInstrs.html
/opt/kgen/docs/llvm/html/GarbageCollection.html
/opt/kgen/docs/llvm/html/GetElementPtr.html
/opt/kgen/docs/llvm/html/GettingStarted.html
/opt/kgen/docs/llvm/html/GettingStartedVS.html
/opt/kgen/docs/llvm/html/GoldPlugin.html
/opt/kgen/docs/llvm/html/HowToReleaseLLVM.html
/opt/kgen/docs/llvm/html/HowToSubmitABug.html
/opt/kgen/docs/llvm/html/LangRef.html
/opt/kgen/docs/llvm/html/Lexicon.html
/opt/kgen/docs/llvm/html/LinkTimeOptimization.html
/opt/kgen/docs/llvm/html/MakefileGuide.html
/opt/kgen/docs/llvm/html/Packaging.html
/opt/kgen/docs/llvm/html/Passes.html
/opt/kgen/docs/llvm/html/ProgrammersManual.html
/opt/kgen/docs/llvm/html/Projects.html
/opt/kgen/docs/llvm/html/ReleaseNotes.html
/opt/kgen/docs/llvm/html/SourceLevelDebugging.html
/opt/kgen/docs/llvm/html/SystemLibrary.html
/opt/kgen/docs/llvm/html/TableGenFundamentals.html
/opt/kgen/docs/llvm/html/TestingGuide.html
/opt/kgen/docs/llvm/html/UsingLibraries.html
/opt/kgen/docs/llvm/html/WritingAnLLVMBackend.html
/opt/kgen/docs/llvm/html/WritingAnLLVMPass.html
/opt/kgen/docs/llvm/html/doxygen.css
/opt/kgen/docs/llvm/html/img/Debugging.gif
/opt/kgen/docs/llvm/html/img/libdeps.gif
/opt/kgen/docs/llvm/html/img/lines.gif
/opt/kgen/docs/llvm/html/img/objdeps.gif
/opt/kgen/docs/llvm/html/img/venusflytrap.jpg
/opt/kgen/docs/llvm/html/index.html
/opt/kgen/docs/llvm/html/llvm.css
/opt/kgen/docs/llvm/html/tutorial/LangImpl1.html
/opt/kgen/docs/llvm/html/tutorial/LangImpl2.html
/opt/kgen/docs/llvm/html/tutorial/LangImpl3.html
/opt/kgen/docs/llvm/html/tutorial/LangImpl4.html
/opt/kgen/docs/llvm/html/tutorial/LangImpl5.html
/opt/kgen/docs/llvm/html/tutorial/LangImpl6.html
/opt/kgen/docs/llvm/html/tutorial/LangImpl7.html
/opt/kgen/docs/llvm/html/tutorial/LangImpl8.html
/opt/kgen/docs/llvm/html/tutorial/OCamlLangImpl1.html
/opt/kgen/docs/llvm/html/tutorial/OCamlLangImpl2.html
/opt/kgen/docs/llvm/html/tutorial/OCamlLangImpl3.html
/opt/kgen/docs/llvm/html/tutorial/OCamlLangImpl4.html
/opt/kgen/docs/llvm/html/tutorial/OCamlLangImpl5.html
/opt/kgen/docs/llvm/html/tutorial/OCamlLangImpl6.html
/opt/kgen/docs/llvm/html/tutorial/OCamlLangImpl7.html
/opt/kgen/docs/llvm/html/tutorial/OCamlLangImpl8.html
/opt/kgen/docs/llvm/html/tutorial/index.html
/opt/kgen/docs/llvm/ps/FileCheck.ps
/opt/kgen/docs/llvm/ps/bugpoint.ps
/opt/kgen/docs/llvm/ps/lit.ps
/opt/kgen/docs/llvm/ps/llc.ps
/opt/kgen/docs/llvm/ps/lli.ps
/opt/kgen/docs/llvm/ps/llvm-ar.ps
/opt/kgen/docs/llvm/ps/llvm-as.ps
/opt/kgen/docs/llvm/ps/llvm-bcanalyzer.ps
/opt/kgen/docs/llvm/ps/llvm-config.ps
/opt/kgen/docs/llvm/ps/llvm-diff.ps
/opt/kgen/docs/llvm/ps/llvm-dis.ps
/opt/kgen/docs/llvm/ps/llvm-extract.ps
/opt/kgen/docs/llvm/ps/llvm-ld.ps
/opt/kgen/docs/llvm/ps/llvm-link.ps
/opt/kgen/docs/llvm/ps/llvm-nm.ps
/opt/kgen/docs/llvm/ps/llvm-prof.ps
/opt/kgen/docs/llvm/ps/llvm-ranlib.ps
/opt/kgen/docs/llvm/ps/llvmc.ps
/opt/kgen/docs/llvm/ps/llvmgcc.ps
/opt/kgen/docs/llvm/ps/llvmgxx.ps
/opt/kgen/docs/llvm/ps/opt.ps
/opt/kgen/docs/llvm/ps/tblgen.ps
/opt/kgen/include/llvm-c/Analysis.h
/opt/kgen/include/llvm-c/BitReader.h
/opt/kgen/include/llvm-c/BitWriter.h
/opt/kgen/include/llvm-c/Core.h
/opt/kgen/include/llvm-c/Disassembler.h
/opt/kgen/include/llvm-c/EnhancedDisassembly.h
/opt/kgen/include/llvm-c/ExecutionEngine.h
/opt/kgen/include/llvm-c/Initialization.h
/opt/kgen/include/llvm-c/LinkTimeOptimizer.h
/opt/kgen/include/llvm-c/Object.h
/opt/kgen/include/llvm-c/Target.h
/opt/kgen/include/llvm-c/Transforms/IPO.h
/opt/kgen/include/llvm-c/Transforms/Scalar.h
/opt/kgen/include/llvm-c/lto.h
/opt/kgen/include/llvm/ADT/APFloat.h
/opt/kgen/include/llvm/ADT/APInt.h
/opt/kgen/include/llvm/ADT/APSInt.h
/opt/kgen/include/llvm/ADT/ArrayRef.h
/opt/kgen/include/llvm/ADT/BitVector.h
/opt/kgen/include/llvm/ADT/DAGDeltaAlgorithm.h
/opt/kgen/include/llvm/ADT/DeltaAlgorithm.h
/opt/kgen/include/llvm/ADT/DenseMap.h
/opt/kgen/include/llvm/ADT/DenseMapInfo.h
/opt/kgen/include/llvm/ADT/DenseSet.h
/opt/kgen/include/llvm/ADT/DepthFirstIterator.h
/opt/kgen/include/llvm/ADT/EquivalenceClasses.h
/opt/kgen/include/llvm/ADT/FoldingSet.h
/opt/kgen/include/llvm/ADT/GraphTraits.h
/opt/kgen/include/llvm/ADT/ImmutableIntervalMap.h
/opt/kgen/include/llvm/ADT/ImmutableList.h
/opt/kgen/include/llvm/ADT/ImmutableMap.h
/opt/kgen/include/llvm/ADT/ImmutableSet.h
/opt/kgen/include/llvm/ADT/InMemoryStruct.h
/opt/kgen/include/llvm/ADT/IndexedMap.h
/opt/kgen/include/llvm/ADT/IntEqClasses.h
/opt/kgen/include/llvm/ADT/IntervalMap.h
/opt/kgen/include/llvm/ADT/IntrusiveRefCntPtr.h
/opt/kgen/include/llvm/ADT/NullablePtr.h
/opt/kgen/include/llvm/ADT/Optional.h
/opt/kgen/include/llvm/ADT/OwningPtr.h
/opt/kgen/include/llvm/ADT/PackedVector.h
/opt/kgen/include/llvm/ADT/PointerIntPair.h
/opt/kgen/include/llvm/ADT/PointerUnion.h
/opt/kgen/include/llvm/ADT/PostOrderIterator.h
/opt/kgen/include/llvm/ADT/PriorityQueue.h
/opt/kgen/include/llvm/ADT/SCCIterator.h
/opt/kgen/include/llvm/ADT/STLExtras.h
/opt/kgen/include/llvm/ADT/ScopedHashTable.h
/opt/kgen/include/llvm/ADT/SetOperations.h
/opt/kgen/include/llvm/ADT/SetVector.h
/opt/kgen/include/llvm/ADT/SmallBitVector.h
/opt/kgen/include/llvm/ADT/SmallPtrSet.h
/opt/kgen/include/llvm/ADT/SmallSet.h
/opt/kgen/include/llvm/ADT/SmallString.h
/opt/kgen/include/llvm/ADT/SmallVector.h
/opt/kgen/include/llvm/ADT/SparseBitVector.h
/opt/kgen/include/llvm/ADT/Statistic.h
/opt/kgen/include/llvm/ADT/StringExtras.h
/opt/kgen/include/llvm/ADT/StringMap.h
/opt/kgen/include/llvm/ADT/StringRef.h
/opt/kgen/include/llvm/ADT/StringSet.h
/opt/kgen/include/llvm/ADT/StringSwitch.h
/opt/kgen/include/llvm/ADT/TinyPtrVector.h
/opt/kgen/include/llvm/ADT/Trie.h
/opt/kgen/include/llvm/ADT/Triple.h
/opt/kgen/include/llvm/ADT/Twine.h
/opt/kgen/include/llvm/ADT/UniqueVector.h
/opt/kgen/include/llvm/ADT/ValueMap.h
/opt/kgen/include/llvm/ADT/VectorExtras.h
/opt/kgen/include/llvm/ADT/ilist.h
/opt/kgen/include/llvm/ADT/ilist_node.h
/opt/kgen/include/llvm/Analysis/AliasAnalysis.h
/opt/kgen/include/llvm/Analysis/AliasSetTracker.h
/opt/kgen/include/llvm/Analysis/BlockFrequencyImpl.h
/opt/kgen/include/llvm/Analysis/BlockFrequencyInfo.h
/opt/kgen/include/llvm/Analysis/BranchProbabilityInfo.h
/opt/kgen/include/llvm/Analysis/CFGPrinter.h
/opt/kgen/include/llvm/Analysis/CallGraph.h
/opt/kgen/include/llvm/Analysis/CaptureTracking.h
/opt/kgen/include/llvm/Analysis/CodeMetrics.h
/opt/kgen/include/llvm/Analysis/ConstantFolding.h
/opt/kgen/include/llvm/Analysis/ConstantsScanner.h
/opt/kgen/include/llvm/Analysis/DIBuilder.h
/opt/kgen/include/llvm/Analysis/DOTGraphTraitsPass.h
/opt/kgen/include/llvm/Analysis/DebugInfo.h
/opt/kgen/include/llvm/Analysis/DomPrinter.h
/opt/kgen/include/llvm/Analysis/DominanceFrontier.h
/opt/kgen/include/llvm/Analysis/DominatorInternals.h
/opt/kgen/include/llvm/Analysis/Dominators.h
/opt/kgen/include/llvm/Analysis/FindUsedTypes.h
/opt/kgen/include/llvm/Analysis/IVUsers.h
/opt/kgen/include/llvm/Analysis/InlineCost.h
/opt/kgen/include/llvm/Analysis/InstructionSimplify.h
/opt/kgen/include/llvm/Analysis/Interval.h
/opt/kgen/include/llvm/Analysis/IntervalIterator.h
/opt/kgen/include/llvm/Analysis/IntervalPartition.h
/opt/kgen/include/llvm/Analysis/LazyValueInfo.h
/opt/kgen/include/llvm/Analysis/LibCallAliasAnalysis.h
/opt/kgen/include/llvm/Analysis/LibCallSemantics.h
/opt/kgen/include/llvm/Analysis/Lint.h
/opt/kgen/include/llvm/Analysis/Loads.h
/opt/kgen/include/llvm/Analysis/LoopDependenceAnalysis.h
/opt/kgen/include/llvm/Analysis/LoopInfo.h
/opt/kgen/include/llvm/Analysis/LoopPass.h
/opt/kgen/include/llvm/Analysis/MemoryBuiltins.h
/opt/kgen/include/llvm/Analysis/MemoryDependenceAnalysis.h
/opt/kgen/include/llvm/Analysis/PHITransAddr.h
/opt/kgen/include/llvm/Analysis/Passes.h
/opt/kgen/include/llvm/Analysis/PathNumbering.h
/opt/kgen/include/llvm/Analysis/PathProfileInfo.h
/opt/kgen/include/llvm/Analysis/PostDominators.h
/opt/kgen/include/llvm/Analysis/ProfileInfo.h
/opt/kgen/include/llvm/Analysis/ProfileInfoLoader.h
/opt/kgen/include/llvm/Analysis/ProfileInfoTypes.h
/opt/kgen/include/llvm/Analysis/RegionInfo.h
/opt/kgen/include/llvm/Analysis/RegionIterator.h
/opt/kgen/include/llvm/Analysis/RegionPass.h
/opt/kgen/include/llvm/Analysis/RegionPrinter.h
/opt/kgen/include/llvm/Analysis/ScalarEvolution.h
/opt/kgen/include/llvm/Analysis/ScalarEvolutionExpander.h
/opt/kgen/include/llvm/Analysis/ScalarEvolutionExpressions.h
/opt/kgen/include/llvm/Analysis/ScalarEvolutionNormalization.h
/opt/kgen/include/llvm/Analysis/SparsePropagation.h
/opt/kgen/include/llvm/Analysis/Trace.h
/opt/kgen/include/llvm/Analysis/ValueTracking.h
/opt/kgen/include/llvm/Analysis/Verifier.h
/opt/kgen/include/llvm/Argument.h
/opt/kgen/include/llvm/Assembly/AssemblyAnnotationWriter.h
/opt/kgen/include/llvm/Assembly/Parser.h
/opt/kgen/include/llvm/Assembly/PrintModulePass.h
/opt/kgen/include/llvm/Assembly/Writer.h
/opt/kgen/include/llvm/Attributes.h
/opt/kgen/include/llvm/AutoUpgrade.h
/opt/kgen/include/llvm/BasicBlock.h
/opt/kgen/include/llvm/Bitcode/Archive.h
/opt/kgen/include/llvm/Bitcode/BitCodes.h
/opt/kgen/include/llvm/Bitcode/BitstreamReader.h
/opt/kgen/include/llvm/Bitcode/BitstreamWriter.h
/opt/kgen/include/llvm/Bitcode/LLVMBitCodes.h
/opt/kgen/include/llvm/Bitcode/ReaderWriter.h
/opt/kgen/include/llvm/CallGraphSCCPass.h
/opt/kgen/include/llvm/CallingConv.h
/opt/kgen/include/llvm/CodeGen/Analysis.h
/opt/kgen/include/llvm/CodeGen/AsmPrinter.h
/opt/kgen/include/llvm/CodeGen/BinaryObject.h
/opt/kgen/include/llvm/CodeGen/CalcSpillWeights.h
/opt/kgen/include/llvm/CodeGen/CallingConvLower.h
/opt/kgen/include/llvm/CodeGen/EdgeBundles.h
/opt/kgen/include/llvm/CodeGen/FastISel.h
/opt/kgen/include/llvm/CodeGen/FunctionLoweringInfo.h
/opt/kgen/include/llvm/CodeGen/GCMetadata.h
/opt/kgen/include/llvm/CodeGen/GCMetadataPrinter.h
/opt/kgen/include/llvm/CodeGen/GCStrategy.h
/opt/kgen/include/llvm/CodeGen/GCs.h
/opt/kgen/include/llvm/CodeGen/ISDOpcodes.h
/opt/kgen/include/llvm/CodeGen/IntrinsicLowering.h
/opt/kgen/include/llvm/CodeGen/JITCodeEmitter.h
/opt/kgen/include/llvm/CodeGen/LatencyPriorityQueue.h
/opt/kgen/include/llvm/CodeGen/LinkAllAsmWriterComponents.h
/opt/kgen/include/llvm/CodeGen/LinkAllCodegenComponents.h
/opt/kgen/include/llvm/CodeGen/LiveInterval.h
/opt/kgen/include/llvm/CodeGen/LiveIntervalAnalysis.h
/opt/kgen/include/llvm/CodeGen/LiveStackAnalysis.h
/opt/kgen/include/llvm/CodeGen/LiveVariables.h
/opt/kgen/include/llvm/CodeGen/MachORelocation.h
/opt/kgen/include/llvm/CodeGen/MachineBasicBlock.h
/opt/kgen/include/llvm/CodeGen/MachineBlockFrequencyInfo.h
/opt/kgen/include/llvm/CodeGen/MachineBranchProbabilityInfo.h
/opt/kgen/include/llvm/CodeGen/MachineCodeEmitter.h
/opt/kgen/include/llvm/CodeGen/MachineCodeInfo.h
/opt/kgen/include/llvm/CodeGen/MachineConstantPool.h
/opt/kgen/include/llvm/CodeGen/MachineDominators.h
/opt/kgen/include/llvm/CodeGen/MachineFrameInfo.h
/opt/kgen/include/llvm/CodeGen/MachineFunction.h
/opt/kgen/include/llvm/CodeGen/MachineFunctionAnalysis.h
/opt/kgen/include/llvm/CodeGen/MachineFunctionPass.h
/opt/kgen/include/llvm/CodeGen/MachineInstr.h
/opt/kgen/include/llvm/CodeGen/MachineInstrBuilder.h
/opt/kgen/include/llvm/CodeGen/MachineJumpTableInfo.h
/opt/kgen/include/llvm/CodeGen/MachineLoopInfo.h
/opt/kgen/include/llvm/CodeGen/MachineLoopRanges.h
/opt/kgen/include/llvm/CodeGen/MachineMemOperand.h
/opt/kgen/include/llvm/CodeGen/MachineModuleInfo.h
/opt/kgen/include/llvm/CodeGen/MachineModuleInfoImpls.h
/opt/kgen/include/llvm/CodeGen/MachineOperand.h
/opt/kgen/include/llvm/CodeGen/MachinePassRegistry.h
/opt/kgen/include/llvm/CodeGen/MachineRegisterInfo.h
/opt/kgen/include/llvm/CodeGen/MachineRelocation.h
/opt/kgen/include/llvm/CodeGen/MachineSSAUpdater.h
/opt/kgen/include/llvm/CodeGen/ObjectCodeEmitter.h
/opt/kgen/include/llvm/CodeGen/PBQP/Graph.h
/opt/kgen/include/llvm/CodeGen/PBQP/HeuristicBase.h
/opt/kgen/include/llvm/CodeGen/PBQP/HeuristicSolver.h
/opt/kgen/include/llvm/CodeGen/PBQP/Heuristics/Briggs.h
/opt/kgen/include/llvm/CodeGen/PBQP/Math.h
/opt/kgen/include/llvm/CodeGen/PBQP/Solution.h
/opt/kgen/include/llvm/CodeGen/Passes.h
/opt/kgen/include/llvm/CodeGen/ProcessImplicitDefs.h
/opt/kgen/include/llvm/CodeGen/PseudoSourceValue.h
/opt/kgen/include/llvm/CodeGen/RegAllocPBQP.h
/opt/kgen/include/llvm/CodeGen/RegAllocRegistry.h
/opt/kgen/include/llvm/CodeGen/RegisterScavenging.h
/opt/kgen/include/llvm/CodeGen/RuntimeLibcalls.h
/opt/kgen/include/llvm/CodeGen/ScheduleDAG.h
/opt/kgen/include/llvm/CodeGen/ScheduleHazardRecognizer.h
/opt/kgen/include/llvm/CodeGen/SchedulerRegistry.h
/opt/kgen/include/llvm/CodeGen/ScoreboardHazardRecognizer.h
/opt/kgen/include/llvm/CodeGen/SelectionDAG.h
/opt/kgen/include/llvm/CodeGen/SelectionDAGISel.h
/opt/kgen/include/llvm/CodeGen/SelectionDAGNodes.h
/opt/kgen/include/llvm/CodeGen/SlotIndexes.h
/opt/kgen/include/llvm/CodeGen/TargetLoweringObjectFileImpl.h
/opt/kgen/include/llvm/CodeGen/ValueTypes.h
/opt/kgen/include/llvm/CodeGen/ValueTypes.td
/opt/kgen/include/llvm/CompilerDriver/Action.h
/opt/kgen/include/llvm/CompilerDriver/AutoGenerated.h
/opt/kgen/include/llvm/CompilerDriver/BuiltinOptions.h
/opt/kgen/include/llvm/CompilerDriver/Common.td
/opt/kgen/include/llvm/CompilerDriver/CompilationGraph.h
/opt/kgen/include/llvm/CompilerDriver/Error.h
/opt/kgen/include/llvm/CompilerDriver/Main.h
/opt/kgen/include/llvm/CompilerDriver/Main.inc
/opt/kgen/include/llvm/CompilerDriver/Tool.h
/opt/kgen/include/llvm/Config/AsmParsers.def
/opt/kgen/include/llvm/Config/AsmPrinters.def
/opt/kgen/include/llvm/Config/Disassemblers.def
/opt/kgen/include/llvm/Config/Targets.def
/opt/kgen/include/llvm/Config/config.h
/opt/kgen/include/llvm/Config/llvm-config.h
/opt/kgen/include/llvm/Constant.h
/opt/kgen/include/llvm/Constants.h
/opt/kgen/include/llvm/DebugInfoProbe.h
/opt/kgen/include/llvm/DefaultPasses.h
/opt/kgen/include/llvm/DerivedTypes.h
/opt/kgen/include/llvm/ExecutionEngine/ExecutionEngine.h
/opt/kgen/include/llvm/ExecutionEngine/GenericValue.h
/opt/kgen/include/llvm/ExecutionEngine/Interpreter.h
/opt/kgen/include/llvm/ExecutionEngine/JIT.h
/opt/kgen/include/llvm/ExecutionEngine/JITEventListener.h
/opt/kgen/include/llvm/ExecutionEngine/JITMemoryManager.h
/opt/kgen/include/llvm/ExecutionEngine/MCJIT.h
/opt/kgen/include/llvm/ExecutionEngine/RuntimeDyld.h
/opt/kgen/include/llvm/Function.h
/opt/kgen/include/llvm/GVMaterializer.h
/opt/kgen/include/llvm/GlobalAlias.h
/opt/kgen/include/llvm/GlobalValue.h
/opt/kgen/include/llvm/GlobalVariable.h
/opt/kgen/include/llvm/InitializePasses.h
/opt/kgen/include/llvm/InlineAsm.h
/opt/kgen/include/llvm/InstrTypes.h
/opt/kgen/include/llvm/Instruction.def
/opt/kgen/include/llvm/Instruction.h
/opt/kgen/include/llvm/Instructions.h
/opt/kgen/include/llvm/IntrinsicInst.h
/opt/kgen/include/llvm/Intrinsics.gen
/opt/kgen/include/llvm/Intrinsics.h
/opt/kgen/include/llvm/Intrinsics.td
/opt/kgen/include/llvm/IntrinsicsARM.td
/opt/kgen/include/llvm/IntrinsicsAlpha.td
/opt/kgen/include/llvm/IntrinsicsCellSPU.td
/opt/kgen/include/llvm/IntrinsicsPTX.td
/opt/kgen/include/llvm/IntrinsicsPowerPC.td
/opt/kgen/include/llvm/IntrinsicsX86.td
/opt/kgen/include/llvm/IntrinsicsXCore.td
/opt/kgen/include/llvm/LLVMContext.h
/opt/kgen/include/llvm/LinkAllPasses.h
/opt/kgen/include/llvm/LinkAllVMCore.h
/opt/kgen/include/llvm/Linker.h
/opt/kgen/include/llvm/MC/EDInstInfo.h
/opt/kgen/include/llvm/MC/MCAsmBackend.h
/opt/kgen/include/llvm/MC/MCAsmInfo.h
/opt/kgen/include/llvm/MC/MCAsmInfoCOFF.h
/opt/kgen/include/llvm/MC/MCAsmInfoDarwin.h
/opt/kgen/include/llvm/MC/MCAsmLayout.h
/opt/kgen/include/llvm/MC/MCAssembler.h
/opt/kgen/include/llvm/MC/MCCodeEmitter.h
/opt/kgen/include/llvm/MC/MCCodeGenInfo.h
/opt/kgen/include/llvm/MC/MCContext.h
/opt/kgen/include/llvm/MC/MCDirectives.h
/opt/kgen/include/llvm/MC/MCDisassembler.h
/opt/kgen/include/llvm/MC/MCDwarf.h
/opt/kgen/include/llvm/MC/MCELFObjectWriter.h
/opt/kgen/include/llvm/MC/MCELFSymbolFlags.h
/opt/kgen/include/llvm/MC/MCExpr.h
/opt/kgen/include/llvm/MC/MCFixup.h
/opt/kgen/include/llvm/MC/MCFixupKindInfo.h
/opt/kgen/include/llvm/MC/MCInst.h
/opt/kgen/include/llvm/MC/MCInstPrinter.h
/opt/kgen/include/llvm/MC/MCInstrDesc.h
/opt/kgen/include/llvm/MC/MCInstrInfo.h
/opt/kgen/include/llvm/MC/MCInstrItineraries.h
/opt/kgen/include/llvm/MC/MCLabel.h
/opt/kgen/include/llvm/MC/MCMachOSymbolFlags.h
/opt/kgen/include/llvm/MC/MCMachObjectWriter.h
/opt/kgen/include/llvm/MC/MCObjectFileInfo.h
/opt/kgen/include/llvm/MC/MCObjectStreamer.h
/opt/kgen/include/llvm/MC/MCObjectWriter.h
/opt/kgen/include/llvm/MC/MCParser/AsmCond.h
/opt/kgen/include/llvm/MC/MCParser/AsmLexer.h
/opt/kgen/include/llvm/MC/MCParser/MCAsmLexer.h
/opt/kgen/include/llvm/MC/MCParser/MCAsmParser.h
/opt/kgen/include/llvm/MC/MCParser/MCAsmParserExtension.h
/opt/kgen/include/llvm/MC/MCParser/MCParsedAsmOperand.h
/opt/kgen/include/llvm/MC/MCRegisterInfo.h
/opt/kgen/include/llvm/MC/MCSection.h
/opt/kgen/include/llvm/MC/MCSectionCOFF.h
/opt/kgen/include/llvm/MC/MCSectionELF.h
/opt/kgen/include/llvm/MC/MCSectionMachO.h
/opt/kgen/include/llvm/MC/MCStreamer.h
/opt/kgen/include/llvm/MC/MCSubtargetInfo.h
/opt/kgen/include/llvm/MC/MCSymbol.h
/opt/kgen/include/llvm/MC/MCTargetAsmLexer.h
/opt/kgen/include/llvm/MC/MCTargetAsmParser.h
/opt/kgen/include/llvm/MC/MCValue.h
/opt/kgen/include/llvm/MC/MCWin64EH.h
/opt/kgen/include/llvm/MC/MachineLocation.h
/opt/kgen/include/llvm/MC/SectionKind.h
/opt/kgen/include/llvm/MC/SubtargetFeature.h
/opt/kgen/include/llvm/Metadata.h
/opt/kgen/include/llvm/Module.h
/opt/kgen/include/llvm/Object/Binary.h
/opt/kgen/include/llvm/Object/COFF.h
/opt/kgen/include/llvm/Object/Error.h
/opt/kgen/include/llvm/Object/MachOFormat.h
/opt/kgen/include/llvm/Object/MachOObject.h
/opt/kgen/include/llvm/Object/ObjectFile.h
/opt/kgen/include/llvm/OperandTraits.h
/opt/kgen/include/llvm/Operator.h
/opt/kgen/include/llvm/Pass.h
/opt/kgen/include/llvm/PassAnalysisSupport.h
/opt/kgen/include/llvm/PassManager.h
/opt/kgen/include/llvm/PassManagers.h
/opt/kgen/include/llvm/PassRegistry.h
/opt/kgen/include/llvm/PassSupport.h
/opt/kgen/include/llvm/Support/AIXDataTypesFix.h
/opt/kgen/include/llvm/Support/AlignOf.h
/opt/kgen/include/llvm/Support/Allocator.h
/opt/kgen/include/llvm/Support/Atomic.h
/opt/kgen/include/llvm/Support/BlockFrequency.h
/opt/kgen/include/llvm/Support/BranchProbability.h
/opt/kgen/include/llvm/Support/CFG.h
/opt/kgen/include/llvm/Support/COFF.h
/opt/kgen/include/llvm/Support/CallSite.h
/opt/kgen/include/llvm/Support/Capacity.h
/opt/kgen/include/llvm/Support/Casting.h
/opt/kgen/include/llvm/Support/CommandLine.h
/opt/kgen/include/llvm/Support/Compiler.h
/opt/kgen/include/llvm/Support/ConstantFolder.h
/opt/kgen/include/llvm/Support/ConstantRange.h
/opt/kgen/include/llvm/Support/CrashRecoveryContext.h
/opt/kgen/include/llvm/Support/DOTGraphTraits.h
/opt/kgen/include/llvm/Support/DataFlow.h
/opt/kgen/include/llvm/Support/DataTypes.h
/opt/kgen/include/llvm/Support/Debug.h
/opt/kgen/include/llvm/Support/DebugLoc.h
/opt/kgen/include/llvm/Support/Disassembler.h
/opt/kgen/include/llvm/Support/Dwarf.h
/opt/kgen/include/llvm/Support/DynamicLibrary.h
/opt/kgen/include/llvm/Support/ELF.h
/opt/kgen/include/llvm/Support/Endian.h
/opt/kgen/include/llvm/Support/Errno.h
/opt/kgen/include/llvm/Support/ErrorHandling.h
/opt/kgen/include/llvm/Support/FEnv.h
/opt/kgen/include/llvm/Support/FileSystem.h
/opt/kgen/include/llvm/Support/FileUtilities.h
/opt/kgen/include/llvm/Support/Format.h
/opt/kgen/include/llvm/Support/FormattedStream.h
/opt/kgen/include/llvm/Support/GetElementPtrTypeIterator.h
/opt/kgen/include/llvm/Support/GraphWriter.h
/opt/kgen/include/llvm/Support/Host.h
/opt/kgen/include/llvm/Support/IRBuilder.h
/opt/kgen/include/llvm/Support/IRReader.h
/opt/kgen/include/llvm/Support/IncludeFile.h
/opt/kgen/include/llvm/Support/InstIterator.h
/opt/kgen/include/llvm/Support/InstVisitor.h
/opt/kgen/include/llvm/Support/LICENSE.TXT
/opt/kgen/include/llvm/Support/LeakDetector.h
/opt/kgen/include/llvm/Support/MachO.h
/opt/kgen/include/llvm/Support/ManagedStatic.h
/opt/kgen/include/llvm/Support/MathExtras.h
/opt/kgen/include/llvm/Support/Memory.h
/opt/kgen/include/llvm/Support/MemoryBuffer.h
/opt/kgen/include/llvm/Support/MemoryObject.h
/opt/kgen/include/llvm/Support/Mutex.h
/opt/kgen/include/llvm/Support/MutexGuard.h
/opt/kgen/include/llvm/Support/NoFolder.h
/opt/kgen/include/llvm/Support/OutputBuffer.h
/opt/kgen/include/llvm/Support/PassManagerBuilder.h
/opt/kgen/include/llvm/Support/PassNameParser.h
/opt/kgen/include/llvm/Support/Path.h
/opt/kgen/include/llvm/Support/PathV1.h
/opt/kgen/include/llvm/Support/PathV2.h
/opt/kgen/include/llvm/Support/PatternMatch.h
/opt/kgen/include/llvm/Support/PluginLoader.h
/opt/kgen/include/llvm/Support/PointerLikeTypeTraits.h
/opt/kgen/include/llvm/Support/PredIteratorCache.h
/opt/kgen/include/llvm/Support/PrettyStackTrace.h
/opt/kgen/include/llvm/Support/Process.h
/opt/kgen/include/llvm/Support/Program.h
/opt/kgen/include/llvm/Support/RWMutex.h
/opt/kgen/include/llvm/Support/Recycler.h
/opt/kgen/include/llvm/Support/RecyclingAllocator.h
/opt/kgen/include/llvm/Support/Regex.h
/opt/kgen/include/llvm/Support/Registry.h
/opt/kgen/include/llvm/Support/RegistryParser.h
/opt/kgen/include/llvm/Support/SMLoc.h
/opt/kgen/include/llvm/Support/Signals.h
/opt/kgen/include/llvm/Support/Solaris.h
/opt/kgen/include/llvm/Support/SourceMgr.h
/opt/kgen/include/llvm/Support/StringPool.h
/opt/kgen/include/llvm/Support/SwapByteOrder.h
/opt/kgen/include/llvm/Support/SystemUtils.h
/opt/kgen/include/llvm/Support/TargetFolder.h
/opt/kgen/include/llvm/Support/ThreadLocal.h
/opt/kgen/include/llvm/Support/Threading.h
/opt/kgen/include/llvm/Support/TimeValue.h
/opt/kgen/include/llvm/Support/Timer.h
/opt/kgen/include/llvm/Support/ToolOutputFile.h
/opt/kgen/include/llvm/Support/TypeBuilder.h
/opt/kgen/include/llvm/Support/Valgrind.h
/opt/kgen/include/llvm/Support/ValueHandle.h
/opt/kgen/include/llvm/Support/Win64EH.h
/opt/kgen/include/llvm/Support/circular_raw_ostream.h
/opt/kgen/include/llvm/Support/raw_os_ostream.h
/opt/kgen/include/llvm/Support/raw_ostream.h
/opt/kgen/include/llvm/Support/system_error.h
/opt/kgen/include/llvm/Support/type_traits.h
/opt/kgen/include/llvm/SymbolTableListTraits.h
/opt/kgen/include/llvm/Target/Mangler.h
/opt/kgen/include/llvm/Target/Target.td
/opt/kgen/include/llvm/Target/TargetCallingConv.h
/opt/kgen/include/llvm/Target/TargetCallingConv.td
/opt/kgen/include/llvm/Target/TargetData.h
/opt/kgen/include/llvm/Target/TargetELFWriterInfo.h
/opt/kgen/include/llvm/Target/TargetFrameLowering.h
/opt/kgen/include/llvm/Target/TargetInstrInfo.h
/opt/kgen/include/llvm/Target/TargetIntrinsicInfo.h
/opt/kgen/include/llvm/Target/TargetJITInfo.h
/opt/kgen/include/llvm/Target/TargetLibraryInfo.h
/opt/kgen/include/llvm/Target/TargetLowering.h
/opt/kgen/include/llvm/Target/TargetLoweringObjectFile.h
/opt/kgen/include/llvm/Target/TargetMachine.h
/opt/kgen/include/llvm/Target/TargetOpcodes.h
/opt/kgen/include/llvm/Target/TargetOptions.h
/opt/kgen/include/llvm/Target/TargetRegisterInfo.h
/opt/kgen/include/llvm/Target/TargetRegistry.h
/opt/kgen/include/llvm/Target/TargetSchedule.td
/opt/kgen/include/llvm/Target/TargetSelect.h
/opt/kgen/include/llvm/Target/TargetSelectionDAG.td
/opt/kgen/include/llvm/Target/TargetSelectionDAGInfo.h
/opt/kgen/include/llvm/Target/TargetSubtargetInfo.h
/opt/kgen/include/llvm/Transforms/IPO.h
/opt/kgen/include/llvm/Transforms/IPO/InlinerPass.h
/opt/kgen/include/llvm/Transforms/Instrumentation.h
/opt/kgen/include/llvm/Transforms/Scalar.h
/opt/kgen/include/llvm/Transforms/Utils/AddrModeMatcher.h
/opt/kgen/include/llvm/Transforms/Utils/BasicBlockUtils.h
/opt/kgen/include/llvm/Transforms/Utils/BasicInliner.h
/opt/kgen/include/llvm/Transforms/Utils/BuildLibCalls.h
/opt/kgen/include/llvm/Transforms/Utils/Cloning.h
/opt/kgen/include/llvm/Transforms/Utils/FunctionUtils.h
/opt/kgen/include/llvm/Transforms/Utils/Local.h
/opt/kgen/include/llvm/Transforms/Utils/PromoteMemToReg.h
/opt/kgen/include/llvm/Transforms/Utils/SSAUpdater.h
/opt/kgen/include/llvm/Transforms/Utils/SSAUpdaterImpl.h
/opt/kgen/include/llvm/Transforms/Utils/UnifyFunctionExitNodes.h
/opt/kgen/include/llvm/Transforms/Utils/UnrollLoop.h
/opt/kgen/include/llvm/Transforms/Utils/ValueMapper.h
/opt/kgen/include/llvm/Type.h
/opt/kgen/include/llvm/Use.h
/opt/kgen/include/llvm/User.h
/opt/kgen/include/llvm/Value.h
/opt/kgen/include/llvm/ValueSymbolTable.h
/opt/kgen/include64/gforscale.dragonegg.mod
/opt/kgen/include64/gforscale.h
/opt/kgen/include64/gforscale.mod
/opt/kgen/lib/BugpointPasses.so
/opt/kgen/lib/LLVMHello.so
/opt/kgen/lib/libLLVMAnalysis.a
/opt/kgen/lib/libLLVMArchive.a
/opt/kgen/lib/libLLVMAsmParser.a
/opt/kgen/lib/libLLVMAsmPrinter.a
/opt/kgen/lib/libLLVMBitReader.a
/opt/kgen/lib/libLLVMBitWriter.a
/opt/kgen/lib/libLLVMCBackend.a
/opt/kgen/lib/libLLVMCBackendInfo.a
/opt/kgen/lib/libLLVMCodeGen.a
/opt/kgen/lib/libLLVMCore.a
/opt/kgen/lib/libLLVMExecutionEngine.a
/opt/kgen/lib/libLLVMInstCombine.a
/opt/kgen/lib/libLLVMInstrumentation.a
/opt/kgen/lib/libLLVMInterpreter.a
/opt/kgen/lib/libLLVMJIT.a
/opt/kgen/lib/libLLVMLinker.a
/opt/kgen/lib/libLLVMMC.a
/opt/kgen/lib/libLLVMMCDisassembler.a
/opt/kgen/lib/libLLVMMCJIT.a
/opt/kgen/lib/libLLVMMCParser.a
/opt/kgen/lib/libLLVMObject.a
/opt/kgen/lib/libLLVMRuntimeDyld.a
/opt/kgen/lib/libLLVMScalarOpts.a
/opt/kgen/lib/libLLVMSelectionDAG.a
/opt/kgen/lib/libLLVMSupport.a
/opt/kgen/lib/libLLVMTarget.a
/opt/kgen/lib/libLLVMTransformUtils.a
/opt/kgen/lib/libLLVMX86AsmParser.a
/opt/kgen/lib/libLLVMX86AsmPrinter.a
/opt/kgen/lib/libLLVMX86CodeGen.a
/opt/kgen/lib/libLLVMX86Desc.a
/opt/kgen/lib/libLLVMX86Disassembler.a
/opt/kgen/lib/libLLVMX86Info.a
/opt/kgen/lib/libLLVMX86Utils.a
/opt/kgen/lib/libLLVMipa.a
/opt/kgen/lib/libLLVMipo.a
/opt/kgen/lib/libLTO.a
/opt/kgen/lib/libgforscale.so
/opt/kgen/lib/libgfortran.a
/opt/kgen/lib/libgfortran.la
/opt/kgen/lib/libgomp.a
/opt/kgen/lib/libgomp.la
/opt/kgen/lib/libgomp.spec
/opt/kgen/lib/libmudflap.a
/opt/kgen/lib/libmudflap.la
/opt/kgen/lib/libmudflapth.a
/opt/kgen/lib/libmudflapth.la
/opt/kgen/lib/libprofile_rt.a
/opt/kgen/lib/libssp.a
/opt/kgen/lib/libssp.la
/opt/kgen/lib/libssp_nonshared.a
/opt/kgen/lib/libssp_nonshared.la
/opt/kgen/lib64/libgforscale.so
/opt/kgen/lib64/libgomp.a
/opt/kgen/lib64/libgomp.la
/opt/kgen/lib64/libmudflap.a
/opt/kgen/lib64/libmudflap.la
/opt/kgen/lib64/libmudflapth.a
/opt/kgen/lib64/libmudflapth.la
/opt/kgen/lib64/libssp.a
/opt/kgen/lib64/libssp.la
/opt/kgen/lib64/libssp_nonshared.a
/opt/kgen/lib64/libssp_nonshared.la
/opt/kgen/opts/gcc.opts
/opt/kgen/opts/kgen-ocl.opts
/opt/kgen/opts/nvcc.opts
/opt/kgen/share/info/dir
/opt/kgen/share/man/man1/bugpoint.1
/opt/kgen/share/man/man1/dragonegg-cpp.1
/opt/kgen/share/man/man1/dragonegg-gcc.1
/opt/kgen/share/man/man1/dragonegg-gcov.1
/opt/kgen/share/man/man1/dragonegg-gfortran.1
/opt/kgen/share/man/man1/lit.1
/opt/kgen/share/man/man1/llc.1
/opt/kgen/share/man/man1/lli.1
/opt/kgen/share/man/man1/llvm-ar.1
/opt/kgen/share/man/man1/llvm-as.1
/opt/kgen/share/man/man1/llvm-bcanalyzer.1
/opt/kgen/share/man/man1/llvm-config.1
/opt/kgen/share/man/man1/llvm-diff.1
/opt/kgen/share/man/man1/llvm-dis.1
/opt/kgen/share/man/man1/llvm-extract.1
/opt/kgen/share/man/man1/llvm-ld.1
/opt/kgen/share/man/man1/llvm-link.1
/opt/kgen/share/man/man1/llvm-nm.1
/opt/kgen/share/man/man1/llvm-prof.1
/opt/kgen/share/man/man1/llvm-ranlib.1
/opt/kgen/share/man/man1/llvmc.1
/opt/kgen/share/man/man1/llvmgcc.1
/opt/kgen/share/man/man1/llvmgxx.1
/opt/kgen/share/man/man1/opt.1
/opt/kgen/share/man/man1/tblgen.1
/opt/kgen/share/man/man7/fsf-funding.7
/opt/kgen/share/man/man7/gfdl.7
/opt/kgen/share/man/man7/gpl.7


%changelog
* Sun Jul 10 2011 Dmitry Mikushin <dmikushin@nvidia.com> 0.1
- initial release
