// Functions that could be directly resolved on the GPU,
// without host callback.

	"abs", "labs", "llabs", "fabs", "fabsf",
	"min", "umin", "llmin", "ullmin", "fminf", "fmin",
	"max", "umax", "llmax", "ullmax", "fmax", "fmax",
	"sin", "sinf",
	"cos", "cosf",
	"sincos", "sincosf",
	"tan", "tanf",
	"sqrt", "sqrtf", "rsqrt", "rsqrtf",
	"exp", "expf", "exp2", "exp2f", "exp10", "exp10f", "expm1", "expm1f",
	"log", "logf", "log2", "log2f", "log10", "log10f", "log1p", "log1pf",
	"floor", "floorf",
	"cosh", "coshf",
	"sinh", "sinhf",
	"tanh", "tanhf",
	"acosh", "acoshf", "asinh", "asinhf", "atanh", "atanhf",
	"ldexp", "ldexpf", "logb", "logbf", "ilogb", "ilogbf",
	"scalbn", "scalbnf", "scalbln", "scalblnf",
	"frexp", "frexpf",
	"round", "roundf", "lround", "lroundf", "llround", "llroundf",
	"rint", "rintf", "lrint", "lrintf", "llrint", "llrintf",
	"nearbyint", "nearbyintf",
	"ceil", "ceilf",
	"trunc", "truncf",
	"fdim", "fdimf",
	"atan", "atanf", "atan2", "atan2f",
	"asin", "asinf",
	"acos", "acosf",
	"hypot", "hypot", "hypotf",
	"cbrt", "cbrtf", "rcbrt", "rcbrtf",
	"sinpi", "sinpif", "cospi", "cospif",
	"pow", "powf",
	"modf", "modff",
	"fmod", "fmodf",
	"remainder", "remainderf", "remquo", "remquof",
	"erf", "erff",
	"erfinv", "erfinvf", "erfc", "erfcf", "erfcinv", "erfcinvf",
	"lgamma", "lgammaf", "tgamma", "tgammaf",
	"copysign", "copysignf",
	"nextafter", "nextafterf", 
	"nan", "nanf",
	"isinf", "__isinf", "__isinff", "__isinfl",
	"isnan", "__isnan", "__isnanf", "__isnanl",
	"isfinite", "__isfinited", "__isfinitef",
	"signbit", "__signbit", "__signbitf", "__signbitd", "__signbitl",
	"__finite", "__finitef",
	"fma", "fmaf",
	"abort",

