#!/usr/bin/perl -w

##
## KGen - the LLVM-based compiler with GPU kernels generation over C backend.
##
## Copyright (c) 2011 Dmitry Mikushin
##
## This software is provided 'as-is', without any express or implied warranty.
## In no event will the authors be held liable for any damages arising 
## from the use of this software.
## Permission is granted to anyone to use this software for any purpose, 
## including commercial applications, and to alter it and redistribute it freely,
## subject to the following restrictions:
##
## 1. The origin of this software must not be misrepresented;
## you must not claim that you wrote the original software.
## If you use this software in a product, an acknowledgment
## in the product documentation would be appreciated but is not required.
## 2. Altered source versions must be plainly marked as such,
## and must not be misrepresented as being the original software.
## 3. This notice may not be removed or altered from any source distribution.
##

if (scalar(@ARGV) != 5)
{
	print "Usage: kgen-install ARCH PREFIX LIB32 LIB64 CUDA_PREFIX\n";
	exit;
}

my($ARCH) = $ARGV[0];
my($PREFIX) = $ARGV[1];
my($LIB32) = $ARGV[2];
my($LIB64) = $ARGV[3];
my($CUDA_PREFIX) = $ARGV[4];

`mkdir -p $PREFIX/bin`;
`mkdir -p $PREFIX/include`;
`mkdir -p $PREFIX/$LIB32`;

if ($ARCH eq "64")
{
	`mkdir -p $PREFIX/include64`;
	`mkdir -p $PREFIX/$LIB64`;
}

#
# Copy binaries to install path.
#
my(@binaries) = (
	"frontend/kernelgen");

foreach $binary (@binaries)
{
	`cp $binary $PREFIX\/bin\/`;
}

#
# Copy includes to install path.
#
my(@includes32) = (
	"runtime/kernelgen.h",
	"runtime/32/kernelgen.mod",
	"runtime/32/kernelgen.kernelgen.mod");
foreach $include (@includes32)
{
	`cp $include $PREFIX\/include\/`;
}
if ($ARCH eq "64")
{
	my(@includes64) = (
		"runtime/kernelgen.h",
		"runtime/64/kernelgen.mod",
		"runtime/64/kernelgen.kernelgen.mod");
	foreach $include (@includes64)
	{
		`cp $include $PREFIX\/include64\/`;
	}
}

#
# Copy libraries to install path.
#
my(@libraries32) = (
	"runtime/32/libkernelgen.so");
foreach $library (@libraries32)
{
	`cp $library $PREFIX\/$LIB32\/`;
}
if ($ARCH eq "64")
{
	my(@libraries64) = (
		"runtime/64/libkernelgen.so");
	foreach $library (@libraries64)
	{
		`cp $library $PREFIX\/$LIB64\/`;
	}
}
