#!/usr/bin/perl -w

##
## KGen - the LLVM-based compiler with GPU kernels generation over C backend.
##
## Copyright (c) 2011 Dmitry Mikushin
##
## This software is provided 'as-is', without any express or implied warranty.
## In no event will the authors be held liable for any damages arising 
## from the use of this software.
## Permission is granted to anyone to use this software for any purpose, 
## including commercial applications, and to alter it and redistribute it freely,
## subject to the following restrictions:
##
## 1. The origin of this software must not be misrepresented;
## you must not claim that you wrote the original software.
## If you use this software in a product, an acknowledgment
## in the product documentation would be appreciated but is not required.
## 2. Altered source versions must be plainly marked as such,
## and must not be misrepresented as being the original software.
## 3. This notice may not be removed or altered from any source distribution.
##

require "KGEN_PREFIX/bin/kgen";

#
# Skip the following Fortran-specific options
# when invoking C compiler frontend.
#
my(@frontend_skipots) = ( qr/-O(\w|\d)+/, qr/-g/ );

#
# Skip the following Fortran-specific options
# when invoking C compiler for backend-generated code.
#
my(@backend_skipopts) = (
	"^-(-|f)all-intrinsics",
	"^-(-|f)free-form",
	"^-(-|f)no-fixed-form",
	"^-(-|f)convert=",
	"^-(-|f)dollar-ok",
	"^-(-|f)implicit-none",
	"^-(-|f)max-identifier-length",
	"^-std=std",
	"^-(-|f)d-lines-as-code",
	"^-(-|f)d-lines-as-comments",
	"^-(-|f)fixed-line-length-n",
	"^-(-|f)fixed-line-length-none",
	"^-(-|f)free-line-length-n",
	"^-(-|f)free-line-length-none",
	"^-(-|f)default-double-8",
	"^-(-|f)default-integer-8",
	"^-(-|f)default-real-8",
	"^-(-|f)cray-pointer",
	"^-(-|f)openmp",
	"^-(-|f)no-range-check",
	"^-(-|f)backslash",
	"^-(-|f)module-private");

kgen("GCC_BIN_PREFIXgfortran", qr/\.(f|f90|F|F90)$/, \@frontend_skipots, \@backend_skipopts);

