#!/usr/bin/perl -w

if (scalar(@ARGV) != 1)
{
	print "Build a list of successfully running kernels\n";
	print "out of kernelgen stats log\n";
	print "Usage: kgen-filter-out <kernelgen.stats>\n";
	exit 0;
}

my($filename) = $ARGV[0];

my(%kernels) = ();

my(@lines) = split("\n", `cat kernelgen.stats`);
foreach $line (@lines)
{
	if ($line =~ m/^R\t(?<NAME>\w+)/)
	{
		my($kernel) = $+{NAME};
		if (!exists($kernels{$kernel}))
		{
			$kernels{$kernel} = 1;
			print "$kernel\n";
		}
	}
}

